version: "3.8"
services:
  db:
    image: postgis/postgis
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: farmdb
    ports:
      - "5432:5432"
    volumes:
      - ./db:/docker-entrypoint-initdb.d

  backend:
    build: ./backend
    command: node server.js
    volumes:
      - ./backend:/app
    ports:
      - "4000:4000"
    depends_on:
      - db
